-- Run this in your Supabase SQL Editor (Dashboard → SQL Editor → New query)

create table if not exists sessions (
  id             bigint generated by default as identity primary key,
  work_date      date not null,
  time_in        text not null,   -- "HH:MM"
  time_out       text not null,   -- "HH:MM"
  lunch_minutes  int  not null default 60,
  notes          text not null default '',
  created_at     timestamptz not null default now()
);

create index if not exists idx_sessions_work_date on sessions(work_date desc);

create table if not exists settings (
  id             int primary key check (id = 1),
  required_hours numeric not null default 486,
  start_date     date not null default '2026-07-13'
);

-- seed the single settings row
insert into settings (id, required_hours, start_date)
values (1, 486, '2026-07-13')
on conflict (id) do nothing;

-- Enable Row Level Security (recommended; allows full access since we use anon key for personal use)
alter table sessions enable row level security;
alter table settings enable row level security;

-- Allow all operations via the anon key (single-user personal app, no auth needed)
create policy "allow all sessions" on sessions for all using (true) with check (true);
create policy "allow all settings" on settings for all using (true) with check (true);
